### ISSUE TITLE
Fix broken CSS

### ISSUE THREAD

**Issue by fantix** [python-gino/python-gino.org#1]
This is from python-gino/gino#664:

- [x] High resolution displayer
- [x] Breadcrumb nav separator
- [x] Breadcrumb nav scroll bar
- [x] Left nav word-wrap

**Comment by notpushkin** [comment]
Also, this:

![image](https://user-images.githubusercontent.com/1298948/84561607-7631f680-ad56-11ea-8448-46d56fa17ce6.png)

(Not sure if I should create a separate issue?)

**Comment by fantix** [comment]
@notpushkin  Thank you so much for the help! This is now fixed.
